# Generated by Django 4.2.13 on 2024-06-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=100)),
                ("fecha_de_nacimiento", models.DateField()),
                ("edad", models.IntegerField()),
                ("sueldo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("rnd", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
    ]
